version: 2.1
orbs:
  hub: yasuhiroki/hub@0.0.2
  jq: circleci/jq@2.2.0
  spruce: sprucelabsai/orb@dev:alpha
jobs:
  test:
    docker:
      - image: circleci/node:16
    working_directory: /mnt/ramdisk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ec:9f:2e:aa:1f:c9:ab:49:57:8f:c0:cd:2e:5b:f3:b0"
      - checkout
      - spruce/checkandskipifnpmpublish
      - spruce/installrsync
      - run: yarn install
      - run: yarn build.ci
      - run: yarn test
      - spruce/exitifnotautoupgrade
      - spruce/mergeautoupgrade
  npm_publish:
    docker:
      - image: circleci/node:16
    working_directory: /mnt/ramdisk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ec:9f:2e:aa:1f:c9:ab:49:57:8f:c0:cd:2e:5b:f3:b0"
      - checkout
      - spruce/checkandskipifnpmpublish
      - spruce/installrsync
      - run: yarn install
      - run: yarn build.dist
      - run: git config --global user.email "$GIT_AUTHOR_EMAIL"
      - run: git config --global user.name "$GIT_AUTHOR_NAME"
      - run: yarn run release
  upgrade:
    docker:
      - image: circleci/node:16
    steps:
      - run:
          name: "Check for auto upgrade"
          command: |
            if [[ -z "$SKIP_DNS_CHECK" ]]; then
              getent hosts autoupgrade.continuoustesting.ai || circleci-agent step halt
            fi
      - add_ssh_keys:
          fingerprints:
            - "ec:9f:2e:aa:1f:c9:ab:49:57:8f:c0:cd:2e:5b:f3:b0"
      - run:
          name: "Check for SSH_KEYS env"
          command: |
            if [[ -n "$SSH_KEYS" ]]; then
              cd ~
              echo $SSH_KEYS | base64 --decode | tar zxf - 
            fi
      - run:
          name: "npm cache"
          command: |
            if [[ -n "$NPM_ENV" ]]; then
              HOSTIP=`/sbin/ip route|awk '/default/ { print $3 }'`
              echo $HOSTIP npmcache.continuoustesting.ai | sudo tee -a /etc/hosts
              npm config set registry http://npmcache.continuoustesting.ai:28080
              npm config set @sprucelabs:registry https://registry.npmjs.org
              npm config set strict-ssl false
            fi
      - checkout
      - hub/install
      - jq/install
      - spruce/settargetbranchenv
      - spruce/installrsync
      - spruce/installcli
      - spruce/upgradecheckformajor
      - spruce/checkfornewlineonlydiff
      - spruce/createpr
workflows:
  version: 2.1
  do_build:
    jobs:
      - test:
          context: public_package_publish
      - npm_publish:
          requires:
            - test
          context: public_package_publish
          filters:
            branches:
              only:
                - master
  upgrade:
    jobs:
      - upgrade:
          context: public_package_publish
          filters:
            branches:
              only:
                - neverRunOnlyForCron
